name: FireBasics Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore FireBasics/FireBasics.sln

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Test the project
      run: dotnet test

    - name: Publish the project
      run: dotnet publish -c Release -o ${{ github.workspace }}/publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Published App
        path: ${{ github.workspace }}/publish
